# Generated by Django 2.2.4 on 2019-08-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190807_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
