# Generated by Django 2.2.4 on 2019-08-07 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
