# Generated by Django 2.2.4 on 2019-10-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfund',
            name='totalAssetValue',
            field=models.FloatField(default=1000000),
        ),
    ]
