# Generated by Django 2.2.4 on 2019-08-11 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0003_delete_stock_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('stock_amount', models.FloatField()),
                ('trading_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Trading_Account')),
            ],
        ),
    ]
