# Generated by Django 2.2.4 on 2019-08-17 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_remove_trading_account_trading_amount'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_amount', models.FloatField()),
                ('market_sold', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=255)),
                ('stock_max', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Stock_Amount',
        ),
        migrations.AddField(
            model_name='shares',
            name='stockID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock'),
        ),
        migrations.AddField(
            model_name='shares',
            name='tradingID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Trading_Account'),
        ),
        migrations.AddField(
            model_name='market',
            name='stockID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock'),
        ),
    ]
