# Generated by Django 2.2.4 on 2019-08-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190817_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_gics',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_ticker',
            field=models.CharField(default='NLL', max_length=10),
        ),
    ]
