# Generated by Django 2.2.4 on 2019-08-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190819_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_amount',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_dayChange',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_price',
            field=models.FloatField(default=200.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_max',
            field=models.FloatField(verbose_name=10.0),
        ),
    ]
