# Generated by Django 2.2.4 on 2019-08-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20190822_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_hasValidInfo',
            field=models.BooleanField(default=False),
        ),
    ]
