# Generated by Django 2.2.4 on 2019-08-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stock_stock_hasvalidinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_amount',
            field=models.IntegerField(default=1000.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_dayChange',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_max',
            field=models.IntegerField(default=1000.0),
        ),
    ]
