# Generated by Django 2.2.4 on 2019-08-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20190823_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_amount',
        ),
    ]
