# Generated by Django 2.2.4 on 2019-08-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_remove_stock_stock_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_max',
            field=models.BigIntegerField(default=1000.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_sold',
            field=models.BigIntegerField(default=0),
        ),
    ]
