# Generated by Django 2.2.4 on 2019-09-09 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0008_auto_20190823_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(choices=[('P', 'Purchased'), ('S', 'Sold')], max_length=1)),
                ('date', models.DateTimeField(auto_now=True)),
                ('shares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Shares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
