# Generated by Django 2.2.4 on 2019-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_transaction_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_history',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
