# Generated by Django 2.2.4 on 2019-09-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_remove_transaction_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_history',
            name='date_of_transaction',
            field=models.CharField(default='21-02', max_length=5),
            preserve_default=False,
        ),
    ]
