# Generated by Django 2.2.4 on 2019-09-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20190909_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_history',
            name='date_of_transaction',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
