# Generated by Django 2.2.4 on 2019-09-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_auto_20190909_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_history',
            name='shares',
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='no_of_shares',
            field=models.FloatField(default=500),
            preserve_default=False,
        ),
    ]
