# Generated by Django 2.2.4 on 2019-09-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20190910_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_history',
            name='stock_gics',
            field=models.CharField(default='test data', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='stock_name',
            field=models.CharField(default='test dat', max_length=100),
            preserve_default=False,
        ),
    ]
