# Generated by Django 2.2.4 on 2019-09-10 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_transaction_history_share_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_history',
            old_name='share_price',
            new_name='stock_price',
        ),
    ]
