# Generated by Django 2.2.4 on 2019-09-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_auto_20190910_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_history',
            name='funds',
            field=models.FloatField(default=2440),
            preserve_default=False,
        ),
    ]
