# Generated by Django 2.2.4 on 2019-10-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_transaction_history_funds'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_history',
            name='trading_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
