language: python
python:
  - "3.6.7"      # current default Python on Travis CI
services:
  - postgresql
env:
  - DJANGO=2.2 DB=postgresql
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python manage.py test
