# Generated by Django 2.2.4 on 2019-08-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trading_account',
            old_name='amount',
            new_name='trading_amount',
        ),
        migrations.AddField(
            model_name='trading_account',
            name='trading_name',
            field=models.CharField(default='trading', max_length=20),
            preserve_default=False,
        ),
    ]
