# Generated by Django 2.2.4 on 2019-08-11 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20190810_0440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock_Amount',
        ),
    ]
