# Generated by Django 2.2.4 on 2019-08-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_delete_stock_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trading_account',
            name='trading_amount',
        ),
    ]
