# Generated by Django 2.2.4 on 2019-09-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_remove_trading_account_trading_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading_account',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
