# Generated by Django 2.2.4 on 2019-09-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fund', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
